### ISSUE TITLE
Input Switcher v1.0.1 not working

### ISSUE THREAD

**Issue by rods321** [axjv/Input-Switcher#1]
After updating to v1.0.1 /inputswitch nothing happens in game

**Comment by axjv** [comment]
There shouldn't be any problem with the code, try reinstalling and seeing if that helps. If you still have trouble, try uninstalling from the addon manager, downloading the ipf file in the repository and placing it in your data folder. Make sure to change the filename by adding a symbol like ☼ to the end.

**Comment by persownage** [comment]
Same thing, i have re-instal the game delete all content, /inputswitch dont work, the chat still say the addon is instaled but its not working, Ps: the previous version was working.
/inputswitch kb
/inputswitch mouse
These two now do nothing whit the new version.

**Comment by Twista** [comment]
The same. Empty command does not do anything, even i got message IS was loaded. This addon is very helpful. If you will get it to work, it will be amazing. Thanks!

**Comment by axjv** [comment]
Updated, please check if it works for you. If you still have problems, include the following:

Does the message input switcher loaded appear?

What messages appear when you type:
/inputswitch
/inputswitch toggle

**Comment by Lazarus-Slate** [comment]
The issue still persists.
The message input switcher loaded appears and it looks like this: http://screencast.com/t/4RypoXfuhm
When I use any of the /inputswitch commands no messages appears nor does anything happen.

**Comment by axjv** [comment]
Another update, see if this works.

**Comment by persownage** [comment]
Now its working for me axjv Omg thanks a lot ! Your addons is fantastic a BIG help to everyone and my 100% thanks. Nice work

**Comment by Lazarus-Slate** [comment]
For me it works fine after the latest update, too. Thank you!
