### ISSUE TITLE
What does /cd alert do?

### ISSUE THREAD

**Issue by excenmille** [axjv/Input-Switcher#12]
Hi, not an issue just a question.

All my abilities alert status are off by default when I /cd list. They all still display the countdown timer when they're about to be ready for use. When I turn a specific skill's alert to on I didn't notice any difference to that skill. 

What does the alert command do?

**Comment by axjv** [comment]
Nice catch, that function wasn't updated from the old version of cdtracker, so it only turned off the text. It should be fixed to disable all alerts from a skill now.
