### ISSUE TITLE
/cd chat doesn't work when /cd skills off

### ISSUE THREAD

**Issue by l3oytoys** [axjv/Input-Switcher#13]
im turnoff /cd skills and buffs and using /cd chat its not countdown is it bug?

**Comment by axjv** [comment]
Turning off skills will turn off all skill messages. If you want the chat to still work, just set the size to 0 (/cd size 0) and leave skills on.

I will change the way this works in the next release.

edit: Update to 2.3.1 to fix this behavior.

**Comment by l3oytoys** [comment]
thanks you!!
