### ISSUE TITLE
Feature Request - Cooldown Tracker

### ISSUE THREAD

**Issue by lona808** [axjv/Input-Switcher#15]
Let me start by saying thank you for creating this addon. It is by far my favorite one out there. You're doing a great job! 

One small thing I would like to see is the option to turn off the "(Spell) ready!" part of the /cd chat command. I love that I don't have to use macros and keybinds anymore for yellow text with spells, but I'd prefer to not have it also show when spells are ready. It's very redundant with the /cd skill and clears casting text as well so sometimes the party won't see Safety Wall cast text. It would also be nice to format the text to our liking. For example, I'd like it to appear as "Heal !!" where another player might wanna do something like "Come here for heals!" Other than that, this addon is PERFECT! 👌🏽

**Comment by axjv** [comment]
This has been added in 2.5.0 with the command /cd chat <ID> <message>.

Cast messages will now stay for 2 seconds before being replaced with anything else.

**Comment by lona808** [comment]
You're the best! The add-on is perfect now. Thank you for the expedient fix.
