### ISSUE TITLE
Persistent Chat - no text input field

### ISSUE THREAD

**Issue by Daist** [axjv/Input-Switcher#19]
Works fine for some time, then the text input field just disappears and never comes back upon pressing Enter. Could only fix it by restarting the game. After uninstalling this addon never saw this problem again, so it must be the cause.

**Comment by axjv** [comment]
Do you have any information about the timing of the bug? Were you happening to be using Whisper?

Try updating to 0.0.2, let me know if it still happens.

**Comment by Daist** [comment]
Oh, no less than half an hour I believe. Might have used whisper, yep. You mean, bug could be caused by a whisper to/from a person who later left the chat? Will try later...

**Comment by Diolik** [comment]
ver 0.0.2 still have issue(

**Comment by Daist** [comment]
Haven't had any issues yet.

**Comment by Diolik** [comment]
bug with whisper still work for me... ver 0.0.2

**Comment by Diolik** [comment]
when change channel or map.. and last chat is whisper or party... enter didn't work, and no text input field, when click friends and click whisper - text field is working.
when change chan or map and last chat is normal - it's ok.

**Comment by axjv** [comment]
The newest game update will break this addon, I'll look into a few potential solutions.

**Comment by axjv** [comment]
Updated for the latest patch.
