### ISSUE TITLE
cdtracker - sound toggle not working properly

### ISSUE THREAD

**Issue by Lazarus-Slate** [axjv/Input-Switcher#2]
It is a really usefull addon but the sound toggle feature seems not be working properly. When using the "/cd sound" command, the sound is switcehd off but after switching channels or maybe also even other "triggers", the sound is back again.

Moreover it always shows the message "CD ready sound off." when you use the "/cd sound" command, like this: http://screencast.com/t/EM7hJLnzd

It would also be very nice if it would be possible to choose from a variety of different sounds in the future.

**Comment by Perlnx** [comment]
Another issue is, when turn on this addon. Sometime skill didnt activate and TP icon disappear but cooldown is already count.

**Comment by axjv** [comment]
Sound toggle fixed, added option to select sound.

See if this version fixes the cooldown count issue. If not please provide a screenshot.

**Comment by Lazarus-Slate** [comment]
For me everything works fine after the latest update ... thank you.
Moreover thank you for the sound select feature!

**Comment by Perlnx** [comment]
As I'm test after lasted update, no cooldown count issue anymore, but still have TP icon disappear some time (And back after change the map).

Another issue with command /cd text, /cd icon, when use to turn off, the icon and text still appear.

**Comment by axjv** [comment]
New version. Check if any of your other addons are disabling the TP button, such as ExtendedUI.
