### ISSUE TITLE
Regen Timer - not working

### ISSUE THREAD

**Issue by Daist** [axjv/Input-Switcher#20]
Spent some SP, regen started (SP bar increased), 'Sit' is displayed on the screen. I sit, numbers count from 0 to 9, then 'Sit' appeared again and never changed afterwards, regardless of the amount of SP and sit/stand up position. 
Logged off, logged on, 'Sit' again. Sat down, again numbers from 0 to 9, 'Sit', then nothing happens (SP was not full). After second log off/log on numbers didn't even appear, just 'Sit'.

**Comment by Daist** [comment]
UPD: Logged in with 500 SP, started working. OMG, it's so amazing, I'm never running out of SP now!!! From time to time, doesn't start the count when I sit down but in 10 minutes it happened once and was fixed by sitting/standing up several times. I'm closing the issue, hope this awesome addon keeps on working. 
Great job, thanks a lot!
UPD2: Looks like I was expecting the timer to start immediately after sitting down, I missed the fact that it only starts working after SP regen tick. Stupid me. It works flawlessly now.

**Comment by Daist** [comment]
UPD3: Changed the channel, addon stopped working. Logged off and on, still not working. 
Restarted the game, works fine again. Changed the channel, counter randomly started, got to 'Sit' and never worked again.
It seems changing the channel stops the addon. Maybe it's possible to add forced restart on detecting channel switch or by timer/command?
UPD4: Changing the map (teleporting to another location) also stops the addon.

**Comment by axjv** [comment]
I'm working on rewriting the whole thing soon, check back in a few days.

**Comment by Daist** [comment]
Great news! By the way, since you're rewriting it, could you check the timer by both hp and sp regen ticks? Because right now it checks for sp only.

**Comment by Questionguy663** [comment]
And uh, can it be made moveable? appologies if it already is but its behind my gear-needs-repair icons at the moment and i can't figure out how to put it where i'd like it.  
I tried Shift Drag, Regular Drag and Control Drag.

**Comment by Diolik** [comment]
regen timer will work if you unchecked option ExtendedUI [Extend Buff Display], that worked for me and regen timer worked correctly.

**Comment by Daist** [comment]
I don't have ExtendedUI installed because it messes up my interface, like randomly hiding party or quest frames and resizing/moving chat frame. Regen timer works fine for me if I restart the game and stay on one map, as long as I don't move to another map or channel.

**Comment by Questionguy663** [comment]
I have the same errors as Daist even without adding ExtendedUI (logging in at full HP / Map Change / Channel Change breaks it)  

But when it does work it's actually one of my **favorite** addons, having something continuously count to 10 for me and sitting makes my character feel like it has some insane regens.  

And with how compact the frame looks with no background if I could move it I would seriously consider just putting the timer right over my characters head

**Comment by axjv** [comment]
Apologies, just got through finals week. After the ktos merger I'll take a look.

**Comment by Questionguy663** [comment]
You're making something great for free, noone expects it to be here until you have free time and feel like making it. Good luck on the results of these finals! :)

**Comment by axjv** [comment]
Updated to 0.0.2, added the ability to drag frames.

**Comment by Daist** [comment]
Thank you very much! Will test now.

**Comment by Daist** [comment]
Works great so far, had the timer window disappear a couple of times for an unknown reason, fixed by switching to another channel.

**Comment by Questionguy663** [comment]
Huh so you can see it Daist? Can you take a picture of what this version looks like because its completely invisible to me :(

**Comment by Daist** [comment]
Sure, it's where it used to be before, but I moved it under my char to be able to see it better. The count starts with a red 0 (zero) (like this http://i.imgur.com/PWiEPeJ.jpg) and increases to 9 gradually turning to green. When it reaches 10, it has '(Sit!)' text added to it (http://i.imgur.com/7Zf9Zs9.jpg) and the count goes on to 20 (until natural standing regen happens), and then back to red 0.

**Comment by Adephx** [comment]
Would just like to add that I am also not seeing the HP regeneration add-on anywhere in my UI.

**Comment by Daist** [comment]
In \TreeOfSavior\addons\regentimer\, do you have settings.json file? Mine contains this (works just fine):

{"lock":0,"pos":{"y":754,"x":888}}

**Comment by Adephx** [comment]
I do, but nada. I used to see it just fine in the previous version.
https://s32.postimg.org/rrjy49rj7/Untitled_1.jpg

**Comment by Daist** [comment]
Have you tried uninstalling it and installing again?

**Comment by Adephx** [comment]
I did :) It might have something to do with my 4k resolution, Extended UI doesn't work correctly on my settings for example.

**Comment by Questionguy663** [comment]
EDIT: Started a seperate Issue Tracker Issue for this instead of invading this one :P

**Comment by excenmille** [comment]
Timer has disappeared for me too after the update. 1080p, not using extended UI.

**Comment by Questionguy663** [comment]
Ah, at least I don't have to plug in a different monitor!
