### ISSUE TITLE
Regen Timer v0.0.3 Invisible but loads in the chat

### ISSUE THREAD

**Issue by Questionguy663** [axjv/Input-Switcher#22]
Hopefully other people can chime in with what resolution you are on, which language version you are playing.   Native Resolution 3440x1440, English version
1. Tested 1920x1080 : Yes
2. Have successfully installed addons before : Yes
3. Tested Reinstall : Yes  
4. Tested Remove Extended UI (+settings files)  : Yes  
5. Tested Manual coordinates in the settings file (x50y50 , x500,y500 , x999y999) : Yes  
6. Tested with no other Addons: Yes  
7. Was Version 1 visible to you: Yes

**Comment by axjv** [comment]
Several people have reported this, I suspect it has something to do with your resolution. To help me get a better idea of what's going on, try this:

Install regen timer. 

Install Excrulon's addon 'Developer Console'. 

When in game, enter /dev into the chat to open the console.

Enter the command REGEN_TIMER_UPDATE() and hit enter. 

Does the console give you any messages? Provide a screenshot if possible.

**Comment by Questionguy663** [comment]
Thank you for taking the time to help, ask me anything else I can try to help fix this and i'll get onto it. 

[string "local regenframe = nil..."]:84: attempt to call field 'lerp' (a nil value)

Here is the screenshot

http://imgur.com/a/aE8Fo

**Comment by axjv** [comment]
See if 0.0.4 works for you.

**Comment by Questionguy663** [comment]
Testing now

**Comment by Questionguy663** [comment]
Works! absolutely perfectly.  
What did you change? In simple terms so I can understand :P

**Comment by axjv** [comment]
'lerp' is a function that isn't there on all machines. When the addon runs into a function that the system cannot find, the rest of the program doesn't run, meaning that the timer never gets shown. I added the 'lerp' function manually so even if your machine doesn't have it, it can use my version and still run properly.

**Comment by Questionguy663** [comment]
that's really intresting, what would it normally be installed / bundled with?

**Comment by axjv** [comment]
It's part of the math library, which should be included with lua (the language addons are written in). Apparently some versions of lua don't include it.

**Comment by Questionguy663** [comment]
Thats strange that my computer didn't have it. Bonus question (last one) what's new in SFX Toggle v0.0.7 from v0.0.6?

**Comment by axjv** [comment]
If you turn it off and change maps it stays off until you enable it again.
