### ISSUE TITLE
SFXtoggle crashing the game when turning it ON

### ISSUE THREAD

**Issue by s1lv3rw0lf** [axjv/Input-Switcher#23]
Hello. 

I was using sfxtoggle normally until today. When i noticed it hasn't reduced the quality to low since i started the game. So i typed /effect then /effect to restart it, then the game crashed. This happens around 2/3 times i've tried.

Things that may be changed from yesterday to today:
- Updated to last version from the addon manager
- Installed Exp viewer

I get the message to send a error report everytime it happens.

Here is the snapshot ToS takes when the error happens. As you can notice, i was typing the command.

https://gyazo.com/875637a1572c71d63055fc364fe4601d

I use 10 - 50 - 100, so it always keeps on low mode, because when it goes to normal mode it turn ons options and end ups slowing it down.

**Comment by axjv** [comment]
Try the new version (0.0.8).

EDIT: Hold on, uploaded the wrong file. Don't update yet.
EDIT2: Try 0.0.9.

**Comment by s1lv3rw0lf** [comment]
Testing for a few minutes toggling now. Seems stable.

One detail is that it always goes to ON when changing channel until it hit the LOW threshold again. That's not too much of an issue. But just to point it out.
