### ISSUE TITLE
As of v0.0.5 the Addon Manager can't update/install the addon

### ISSUE THREAD

**Issue by allysson-david** [axjv/Input-Switcher#29]
Just as the title says.
As of v0.0.5 the Addon Manager can't update/install the addon.

You named the IPF file: assortment_v0.0.5.ipf [[here](https://github.com/axjv/Input-Switcher/releases/tag/strawberry)]
It should have been: assortment-v0.0.5.ipf

**Comment by axjv** [comment]
You're right, I made a typo in the filename, try again and it should work.

**Comment by luisceccon** [comment]
Hello!
I still can't install the assortment addon using the Addon Manager.
In TreeOfSavior/data there is a file named "_assortment-⛄-v0.0.5.ipf"
In the TreeOfSavior\addons\assortment\addon_d.ipf\assortment there are 3 files: 
a) settings.json
b) assortment.lua
c) assortment.xml.
What's is wrong?
Can you help me?
Tks

**Comment by allysson-david** [comment]
@luisceccon As of the big update that changed the inventory to contain two tabs the Assortment addon stopped working. And its development has been stopped. Just forget it. :/
