### ISSUE TITLE
Low and Freeze FPS after install addon

### ISSUE THREAD

**Issue by FeLiPe-Eduardo** [axjv/Input-Switcher#3]
after installed the addon and I was low and freeze fps ,after the addon has been removed, returned to normal

PC Config:
CPU : AMD FX-9590 
Motherboard : Crosshair V Formula 
GPU : Gigabyte Geforce GTX970 G1 
GPU 2 : Radeon HIS AMD HD6970 
Memory Ram :16gb 4x Corsair Vengeance 4gb 1600mhz 
Power Supply : Corsair HX850 850w 
Watercooler H100i Corsair 
Cooler Memory Ram : Airflow II Corsair 
Case : Corsair R500 
HD: SSD 128gb Corsair Force Series™ LX (RAID 0) 
HD: SSD 120gb Kingston V300 (RAID 0) 
HD : Sata III 500gb 
HD : Sata III 500gb 
HD: Sata II 160gb 

Windows 10

**Comment by axjv** [comment]
Check if any other addons are causing this problem, other user reports show no frame drops, even on low end machines.

If you believe that it is this addon in particular, please attach a screenshot of when the issues occur so that I can diagnose the problem.
