### ISSUE TITLE
Buffs timer and enable/disable

### ISSUE THREAD

**Issue by mateusb12** [axjv/Input-Switcher#5]
Hey dude, two suggestions to improve this addon ^^ 

enable / disable the skills that you want to track the cooldown
track the timeduration of buffs too, because there are some skills that the duration of the buff is sooo loonger than the cooldown of the skill (example: concentrate)

**Comment by axjv** [comment]
Thank you for your feedback. Currently you can enable certain skills by first typing `/cd list` to get a list of your skills along with their ID numbers, and then `/cd alert <ID number>` to toggle alerts on or off for a specific skill. You can also type `/cd chat <ID number>` to enable or disable chat alerts, which basically tell your team when your skill will be up. The command `/cd list` also tells you if you have alerts/chat alerts on or off. If you wish to reset all settings, you can use `/cd reset`.

I will look into adding a buff tracker feature.

**Comment by mateusb12** [comment]
Oh, sorry, i didn't knew about this feature
Anyway, thanks for the answer ^^
