### ISSUE TITLE
cdtracker: Not working when resting (insert key)

### ISSUE THREAD

**Issue by Lazarus-Slate** [axjv/Input-Switcher#6]
The cdtracker addon does not work when you are resting (default key: insert). It does not notify about cooldowns which are (about to get) ready again.

However I'm not sure if this is a real bug because I think the addon receives the data about the according cooldowns from the usual hotkey bar which simply is not present while resting. So maybe it might be technically impossible to notify about cooldowns while resting. But if it's not, it would be great, if this could be done.

**Comment by axjv** [comment]
This feature has been pushed to the latest release.

**Comment by Lazarus-Slate** [comment]
Great, works fine for me ... thank you!
