### ISSUE TITLE
cdtracker: Occasionally displaying skill cooldowns twice

### ISSUE THREAD

**Issue by Lazarus-Slate** [axjv/Input-Switcher#7]
At least for the Fireball skill (Pyromancer), the cooldown is displayed twice all the time:
http://screencast.com/t/FhejfvgMCKA8

I did not see this along with other skills up to now but maybe it happens for others, too.

First I thought it might be related with the 2 charges of this skill but it works fine for other skills with multiple charges. I tested it with Swell Body (Thaumaturge) which also has 2 charges and it worked fine.

**Comment by axjv** [comment]
Please check if Fireball is assigned to 2 slots on your skill bar.

**Comment by Lazarus-Slate** [comment]
That's exactly the case! Sometimes it's that simple.

However, the addon should take this into account and not display the CD 2 times when the same skill is assigned to several time to the skill bar. Only if technically possible of course.

**Comment by axjv** [comment]
Fixed in 2.3.
