### ISSUE TITLE
cdtracker: Feature request - positioning

### ISSUE THREAD

**Issue by Lazarus-Slate** [axjv/Input-Switcher#8]
It would be great if it would be possible to position the frames via mouse. Maybe an integration with the ExtendedUI addon might be possible, too.

If none of the above mentioned is possible, it would at least be nice if there could be something like a test or positioning mode which (upon activation) permanently shows the frames so that it would be easier to position them. This would be helpful for testing the different skins, too.

**Comment by axjv** [comment]
The latest beta includes this feature.

**Comment by Lazarus-Slate** [comment]
Oh sorry ... I just realized that the frames can be moved via mouse drag and drop already.

Anyway, is there also a way (maybe a chat command I missed) to permanently display all cdtracker related frames for positioning purpose?

**Comment by axjv** [comment]
Not at the moment. I'll add it to my list.

**Comment by axjv** [comment]
Show frames has been added in 2.4.0, command is /cd showframes
